modLoader="kotlinforforge"
loaderVersion="${kff_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Luligabi1/HostileNeuralIndustrialization/issues/"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/Luligabi1/HostileNeuralIndustrialization/"
logoFile="assets/${mod_id}/logo.png"
authors="${mod_authors}"
description='''${mod_description}'''

[[mixins]]
config="${mod_id}.mixins.json"

# The [[accessTransformers]] block allows you to declare where your AT file is.
#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="modern_industrialization"
    type="required"
    versionRange="${modern_industrialization_version_range}"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="hostilenetworks"
    type="required"
    versionRange="${hnn_version_range}"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="tesseract_api"
    type="required"
    versionRange="${tesseract_version_range}"
    ordering="AFTER"
    side="BOTH"